--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KienMCVN/OnlineTime
build-by-default: true
branches:
- main
projects:
  OnlineTime:
    path: ""
    icon: clock.png
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.0
        branch: "master"
...
