name: OnlineTime
main: KienMC\OnlTime\Main
api: 5.0.0
version: 0.0.1
author:
- KienDev
github: https://github.com/KienMCVN/
description: Plugin OnlineTime Code By KienDev
virions: ["FormAPI"]
commands:
   onlinetime:
      description: "See Top Online"
      permission: onlinetime.cmd
      aliases: ["toponline","toponl","onltime"]
permissions:
   onlinetime.cmd:
      default: true
